### ISSUE TITLE
evaluate the  "absorberCorrection"

### ISSUE THREAD

**Issue by shaojunlu** [iLCSoft/DDMarlinPandora#10]
Since DDCaloHitCreator.cc has been used by  CLIC and ILD.
I would like to generate  an issue here for the so-called "absorberCorrection".

https://github.com/iLCSoft/DDMarlinPandora/blob/master/src/DDCaloHitCreator.cc#L188-#L191

I do not think that this is a feature what we want to use.

From my understanding, it generate some new weight for the deferent layers to select the CalorimeterHit which has already done in the MarlinProcessor CaloDigi/CaloReco for the "MipThreshold".

I did not think that to apply the "MipThreshold" again is wrong, but the "absorberCorrection" actually changed the "MipThreshold" value within the same detector for the different CalorimeterHit.
I doubt that it will affect our calorimeter reconstruction, and then may affect the JER.

I think that we should remove all the "absorberCorrection" from this code.
Or did I misunderstand the so-called "absorberCorrection".

**Comment by andresailer** [comment]
As the absorber correction depends on the layer absober thicknesses and is not constant for a calorimeter one should understand better what is going on before this logic is ripped out. At the very least a re-calibration is needed after this change.

**Comment by shaojunlu** [comment]
Let's say there is a signal from Silicon, which has E_hit.
First, sud-detector experts provide CaloDigi/CaloReco, which decide if E_hit > 0.5 MIP, they want to keep it and use it. Then predict the total energy depends on the absorber thickness in front of it with this signal by a factor. 
I understand, if the sud-detector want to keep the signal with E_hit > 0.3 MIP, they need a smaller factor to recover the true energy.

Now, come to the DDMarlinPandora, it check the "E_hit" with "0.5 MIP" again. And what are the logic why the absorber thickness decides this Silicon signal will used or not.

Yes, re-calibration will be needed after this change to recover the true energy.

**Comment by danieljeans** [comment]
DDMarlinPandora is looking at hit energies from the digitiser, including an absorber correction.

I wonder if this absorberCorrection is to convert the energy back to the "sensitive layer only" energy (i.e. the simhit energy)? I think an energy threshold (whose role is to simulate the removal of low energy noise hits) should be applied to this sensitive layer energy, rather than after absorber correction.

whether we need such a hit energy threshold in both the digitiser and ddmarlinpandora  seems unlikely to me, unless I understand it's role in ddmarlinpandora.

**Comment by shaojunlu** [comment]
I agree with Andrea, we should understand better what is going on before this logic is ripped out.

I think , we may try to set "MipThreshold" to 0.0 in the steering file for DDMarlinPandora to check our reconstruction. 
That means DDCaloHitCreator.cc will accept all hit provided by CaloDig/CaloReco MarlinProcessors.

**Comment by shaojunlu** [comment]
There are also  Ecal Gap contributions which provide by "BruteForceEcalGapFiller" MarlinProcessor. 

Depends on how the EcalGap contributions were defined for their energy, position and type, it may affect both the Ecal calibrations (are they ECAL type hits?) and Ecal reconstructions (do they pass "MipThreshold"?).
