### ISSUE TITLE
SoftwareCompensationTraining

### ISSUE THREAD

**Issue by linghuiliu** [iLCSoft/DDMarlinPandora#18]
I found that on ILCSOFT v02-00-01, software compensation training had some trouble.
When I set "PandoraSettingsSoftwareCompensationTraining.xml" for the Pandora settings file to create the root tree for the training, DDMarlin complaint as:
```code
[ VERBOSE "MyDDMarlinPandora"] LCContent::RegisterSoftwareCompensationEnergyCorrection(*m_pPandora, "SoftwareCompensation", softwareCompensationParameters) return STATUS_CODE_ALREADY_PRESENT
[ VERBOSE "MyDDMarlinPandora"]     in function: RegisterUserComponents
[ VERBOSE "MyDDMarlinPandora"]     in file:     /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01/DDMarlinPandora/v00-10/src/DDPandoraPFANewProcessor.cc line#: 329
```
It seems it is due to the software compensation now applied in the pandoraPFA officially unlike v01-16, that I confirmed the training was working.

**Comment by oviazlo** [comment]
Hello. I was running Software compensation training just a few days ago with CLD (FCCee) detector and it was working fine for me. I was using the latest iLCSoft build by 2018-10-11.
I put an example of a job which I have been using here:
/afs/cern.ch/work/v/viazlo/public/SoftwareCompensationTraining.tgz
one can just run marlin_ILCSoft-2018-10-11_gcc62_Run_1.sh script to get root tree

**Comment by linghuiliu** [comment]
Yes, I could also get a tree with your script, but not with our ILD detector.
The two look not compatible and the problem is still there.

**Comment by linghuiliu** [comment]
It could be resolved by modifying some of the paths. Thank you very much.
